name: continuous integration

on:
  push:
    paths:
      - features/**
      - .github/workflows/ci.yml
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: |
          ./scripts/unit-tests-verify.sh
      - name: Validate Step Definitions
        run: |
          ./scripts/specs-verify.sh
      - name: Genereer test rapportage
        if: always()
        run: |
          node ./scripts/generate-cucumber-reports.js
      - name: Upload test rapportage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: test-reports
